# Generated by Django 4.1 on 2023-06-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('follower', models.CharField(max_length=50, null=True)),
                ('follows', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_posted', models.DateField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
