# Generated by Django 4.1 on 2023-06-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuzzBird', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='username_id',
        ),
    ]
